<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace Tests\Stubs\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AddressMessage</code>
 */
class AddressMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string city = 1;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string street = 2;</code>
     */
    protected $street = '';
    /**
     * Generated from protobuf field <code>.DistrictMessage district = 3;</code>
     */
    protected $district = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $city
     *     @type string $street
     *     @type \Tests\Stubs\Messages\DistrictMessage $district
     * }
     */
    public function __construct($data = NULL) {
        \Tests\Stubs\Messages\GPBMetadata\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string city = 1;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street = 2;</code>
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Generated from protobuf field <code>string street = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->street = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DistrictMessage district = 3;</code>
     * @return \Tests\Stubs\Messages\DistrictMessage|null
     */
    public function getDistrict()
    {
        return $this->district;
    }

    public function hasDistrict()
    {
        return isset($this->district);
    }

    public function clearDistrict()
    {
        unset($this->district);
    }

    /**
     * Generated from protobuf field <code>.DistrictMessage district = 3;</code>
     * @param \Tests\Stubs\Messages\DistrictMessage $var
     * @return $this
     */
    public function setDistrict($var)
    {
        GPBUtil::checkMessage($var, \Tests\Stubs\Messages\DistrictMessage::class);
        $this->district = $var;

        return $this;
    }

}

