<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace Tests\Stubs\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserMessage</code>
 */
class UserMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.AddressMessage address = 3;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>repeated .PostMessage posts = 4;</code>
     */
    private $posts;
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type \Tests\Stubs\Messages\AddressMessage $address
     *     @type array<\Tests\Stubs\Messages\PostMessage>|\Google\Protobuf\Internal\RepeatedField $posts
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     * }
     */
    public function __construct($data = NULL) {
        \Tests\Stubs\Messages\GPBMetadata\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AddressMessage address = 3;</code>
     * @return \Tests\Stubs\Messages\AddressMessage|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.AddressMessage address = 3;</code>
     * @param \Tests\Stubs\Messages\AddressMessage $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Tests\Stubs\Messages\AddressMessage::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PostMessage posts = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPosts()
    {
        return $this->posts;
    }

    /**
     * Generated from protobuf field <code>repeated .PostMessage posts = 4;</code>
     * @param array<\Tests\Stubs\Messages\PostMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPosts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tests\Stubs\Messages\PostMessage::class);
        $this->posts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

